// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  ApiRootApiGet2Data,
  ApiRootApiGet2Responses,
  ApiRootApiGetData,
  ApiRootApiGetResponses,
  AuthenticateApiAuthGetData,
  AuthenticateApiAuthGetResponses,
  CheckDbApiDbGetData,
  CheckDbApiDbGetResponses,
  CreateFeedbackApiFeedbackPostData,
  CreateFeedbackApiFeedbackPostErrors,
  CreateFeedbackApiFeedbackPostResponses,
  CreateProductApiSampleProductPostData,
  CreateProductApiSampleProductPostErrors,
  CreateProductApiSampleProductPostResponses,
  DeleteProductApiSampleProductProductIdDeleteData,
  DeleteProductApiSampleProductProductIdDeleteErrors,
  DeleteProductApiSampleProductProductIdDeleteResponses,
  DownloadFileApiFileGetData,
  DownloadFileApiFileGetErrors,
  DownloadFileApiFileGetResponses,
  GetProductApiSampleProductProductIdGetData,
  GetProductApiSampleProductProductIdGetErrors,
  GetProductApiSampleProductProductIdGetResponses,
  GetProductsApiSampleProductGetData,
  GetProductsApiSampleProductGetResponses,
  UpdateProductApiSampleProductProductIdPutData,
  UpdateProductApiSampleProductProductIdPutErrors,
  UpdateProductApiSampleProductProductIdPutResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Api Root
 *
 * Get the root of the API.
 */
export const apiRootApiGet = <ThrowOnError extends boolean = false>(
  options?: Options<ApiRootApiGetData, ThrowOnError>,
): RequestResult<ApiRootApiGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ApiRootApiGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api",
    ...options,
  });

/**
 * Api Root
 *
 * Get the root of the API.
 */
export const apiRootApiGet2 = <ThrowOnError extends boolean = false>(
  options?: Options<ApiRootApiGet2Data, ThrowOnError>,
): RequestResult<ApiRootApiGet2Responses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    ApiRootApiGet2Responses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/",
    ...options,
  });

/**
 * Authenticate
 *
 * Authenticate.
 */
export const authenticateApiAuthGet = <ThrowOnError extends boolean = false>(
  options?: Options<AuthenticateApiAuthGetData, ThrowOnError>,
): RequestResult<AuthenticateApiAuthGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    AuthenticateApiAuthGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/auth",
    ...options,
  });

/**
 * Check Db
 *
 * Check if the database is responding.
 */
export const checkDbApiDbGet = <ThrowOnError extends boolean = false>(
  options?: Options<CheckDbApiDbGetData, ThrowOnError>,
): RequestResult<CheckDbApiDbGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<
    CheckDbApiDbGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/db",
    ...options,
  });

/**
 * Download File
 *
 * Generate temporary download links to files on a set bucket.
 *
 * :param file_path: Path to file to download.
 * :return: File content.
 */
export const downloadFileApiFileGet = <ThrowOnError extends boolean = false>(
  options: Options<DownloadFileApiFileGetData, ThrowOnError>,
): RequestResult<
  DownloadFileApiFileGetResponses,
  DownloadFileApiFileGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    DownloadFileApiFileGetResponses,
    DownloadFileApiFileGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/file",
    ...options,
  });

/**
 * Create Feedback
 *
 * Send feedback.
 *
 * :param user: user.
 * :param feedback: Feedback to send.
 */
export const createFeedbackApiFeedbackPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateFeedbackApiFeedbackPostData, ThrowOnError>,
): RequestResult<
  CreateFeedbackApiFeedbackPostResponses,
  CreateFeedbackApiFeedbackPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateFeedbackApiFeedbackPostResponses,
    CreateFeedbackApiFeedbackPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/feedback",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Products
 *
 * Get all products.
 *
 * :return: All products.
 */
export const getProductsApiSampleProductGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetProductsApiSampleProductGetData, ThrowOnError>,
): RequestResult<
  GetProductsApiSampleProductGetResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetProductsApiSampleProductGetResponses,
    unknown,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/sample/products",
    ...options,
  });

/**
 * Create Product
 *
 * Create a product.
 *
 * :param product: Product to create.
 * :return: Newly created product.
 */
export const createProductApiSampleProductPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateProductApiSampleProductPostData, ThrowOnError>,
): RequestResult<
  CreateProductApiSampleProductPostResponses,
  CreateProductApiSampleProductPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateProductApiSampleProductPostResponses,
    CreateProductApiSampleProductPostErrors,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/sample/products",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Product
 *
 * Delete a product.
 *
 * :param product_id: ID of the product to delete.
 */
export const deleteProductApiSampleProductProductIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteProductApiSampleProductProductIdDeleteData,
    ThrowOnError
  >,
): RequestResult<
  DeleteProductApiSampleProductProductIdDeleteResponses,
  DeleteProductApiSampleProductProductIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteProductApiSampleProductProductIdDeleteResponses,
    DeleteProductApiSampleProductProductIdDeleteErrors,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/sample/products/{product_id}",
    ...options,
  });

/**
 * Get Product
 *
 * Get a single product.
 *
 * :param product_id: ID of the product to retrieve.
 * :return: Product matching the provided ID.
 */
export const getProductApiSampleProductProductIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetProductApiSampleProductProductIdGetData, ThrowOnError>,
): RequestResult<
  GetProductApiSampleProductProductIdGetResponses,
  GetProductApiSampleProductProductIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetProductApiSampleProductProductIdGetResponses,
    GetProductApiSampleProductProductIdGetErrors,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/sample/products/{product_id}",
    ...options,
  });

/**
 * Update Product
 *
 * Update a product.
 *
 * :param product: Product to update.
 * :return: Updated product.
 */
export const updateProductApiSampleProductProductIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateProductApiSampleProductProductIdPutData, ThrowOnError>,
): RequestResult<
  UpdateProductApiSampleProductProductIdPutResponses,
  UpdateProductApiSampleProductProductIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateProductApiSampleProductProductIdPutResponses,
    UpdateProductApiSampleProductProductIdPutErrors,
    ThrowOnError
  >({
    security: [{ scheme: "basic", type: "http" }],
    url: "/api/sample/products/{product_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
