// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Feedback
 *
 * DTO to represent a feedback.
 *
 * :param feedback_message: Feedback message.
 * :param url_path: Path to the page on which the feedback was submitted.
 */
export type Feedback = {
  /**
   * Feedback Message
   */
  feedback_message: string;
  /**
   * Url Path
   */
  url_path: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * Product
 *
 * DTO to represent a product.
 *
 * :param product_id: Product ID.
 * :param product_name: Name of the product.
 * :param color: Product color.
 * :param price: Product price.
 */
export type Product = {
  /**
   * Product Id
   */
  product_id?: number | null;
  /**
   * Product Name
   */
  product_name: string;
  /**
   * Color
   */
  color: string;
  /**
   * Price
   */
  price: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type ApiRootApiGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api";
};

export type ApiRootApiGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ApiRootApiGet2Data = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/";
};

export type ApiRootApiGet2Responses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type AuthenticateApiAuthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/auth";
};

export type AuthenticateApiAuthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type CheckDbApiDbGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/db";
};

export type CheckDbApiDbGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DownloadFileApiFileGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * File Path
     */
    file_path: string;
  };
  url: "/api/file";
};

export type DownloadFileApiFileGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DownloadFileApiFileGetError =
  DownloadFileApiFileGetErrors[keyof DownloadFileApiFileGetErrors];

export type DownloadFileApiFileGetResponses = {
  /**
   * Successful Response
   */
  200: string;
};

export type DownloadFileApiFileGetResponse =
  DownloadFileApiFileGetResponses[keyof DownloadFileApiFileGetResponses];

export type CreateFeedbackApiFeedbackPostData = {
  body: Feedback;
  path?: never;
  query?: never;
  url: "/api/feedback";
};

export type CreateFeedbackApiFeedbackPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateFeedbackApiFeedbackPostError =
  CreateFeedbackApiFeedbackPostErrors[keyof CreateFeedbackApiFeedbackPostErrors];

export type CreateFeedbackApiFeedbackPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetProductsApiSampleProductGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/sample/products";
};

export type GetProductsApiSampleProductGetResponses = {
  /**
   * Response Get Products Api Sample Product Get
   *
   * Successful Response
   */
  200: Array<Product>;
};

export type GetProductsApiSampleProductGetResponse =
  GetProductsApiSampleProductGetResponses[keyof GetProductsApiSampleProductGetResponses];

export type CreateProductApiSampleProductPostData = {
  body: Product;
  path?: never;
  query?: never;
  url: "/api/sample/products";
};

export type CreateProductApiSampleProductPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateProductApiSampleProductPostError =
  CreateProductApiSampleProductPostErrors[keyof CreateProductApiSampleProductPostErrors];

export type CreateProductApiSampleProductPostResponses = {
  /**
   * Successful Response
   */
  200: Product;
};

export type CreateProductApiSampleProductPostResponse =
  CreateProductApiSampleProductPostResponses[keyof CreateProductApiSampleProductPostResponses];

export type DeleteProductApiSampleProductProductIdDeleteData = {
  body?: never;
  path: {
    /**
     * Product Id
     */
    product_id: number;
  };
  query?: never;
  url: "/api/sample/products/{product_id}";
};

export type DeleteProductApiSampleProductProductIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteProductApiSampleProductProductIdDeleteError =
  DeleteProductApiSampleProductProductIdDeleteErrors[keyof DeleteProductApiSampleProductProductIdDeleteErrors];

export type DeleteProductApiSampleProductProductIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetProductApiSampleProductProductIdGetData = {
  body?: never;
  path: {
    /**
     * Product Id
     */
    product_id: number;
  };
  query?: never;
  url: "/api/sample/products/{product_id}";
};

export type GetProductApiSampleProductProductIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetProductApiSampleProductProductIdGetError =
  GetProductApiSampleProductProductIdGetErrors[keyof GetProductApiSampleProductProductIdGetErrors];

export type GetProductApiSampleProductProductIdGetResponses = {
  /**
   * Successful Response
   */
  200: Product;
};

export type GetProductApiSampleProductProductIdGetResponse =
  GetProductApiSampleProductProductIdGetResponses[keyof GetProductApiSampleProductProductIdGetResponses];

export type UpdateProductApiSampleProductProductIdPutData = {
  body: Product;
  path: {
    /**
     * Product Id
     */
    product_id: string;
  };
  query?: never;
  url: "/api/sample/products/{product_id}";
};

export type UpdateProductApiSampleProductProductIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateProductApiSampleProductProductIdPutError =
  UpdateProductApiSampleProductProductIdPutErrors[keyof UpdateProductApiSampleProductProductIdPutErrors];

export type UpdateProductApiSampleProductProductIdPutResponses = {
  /**
   * Successful Response
   */
  200: Product;
};

export type UpdateProductApiSampleProductProductIdPutResponse =
  UpdateProductApiSampleProductProductIdPutResponses[keyof UpdateProductApiSampleProductProductIdPutResponses];
